// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: testhellochain/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryShowvenuesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryShowvenuesRequest) Reset()         { *m = QueryShowvenuesRequest{} }
func (m *QueryShowvenuesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryShowvenuesRequest) ProtoMessage()    {}
func (*QueryShowvenuesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{2}
}
func (m *QueryShowvenuesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowvenuesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowvenuesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowvenuesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowvenuesRequest.Merge(m, src)
}
func (m *QueryShowvenuesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowvenuesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowvenuesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowvenuesRequest proto.InternalMessageInfo

func (m *QueryShowvenuesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryShowvenuesResponse struct {
	Venue      []*Venue            `protobuf:"bytes,1,rep,name=Venue,proto3" json:"Venue,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryShowvenuesResponse) Reset()         { *m = QueryShowvenuesResponse{} }
func (m *QueryShowvenuesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryShowvenuesResponse) ProtoMessage()    {}
func (*QueryShowvenuesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{3}
}
func (m *QueryShowvenuesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryShowvenuesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryShowvenuesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryShowvenuesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryShowvenuesResponse.Merge(m, src)
}
func (m *QueryShowvenuesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryShowvenuesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryShowvenuesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryShowvenuesResponse proto.InternalMessageInfo

func (m *QueryShowvenuesResponse) GetVenue() []*Venue {
	if m != nil {
		return m.Venue
	}
	return nil
}

func (m *QueryShowvenuesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryCallapiRequest struct {
}

func (m *QueryCallapiRequest) Reset()         { *m = QueryCallapiRequest{} }
func (m *QueryCallapiRequest) String() string { return proto.CompactTextString(m) }
func (*QueryCallapiRequest) ProtoMessage()    {}
func (*QueryCallapiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{4}
}
func (m *QueryCallapiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCallapiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCallapiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCallapiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCallapiRequest.Merge(m, src)
}
func (m *QueryCallapiRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryCallapiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCallapiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCallapiRequest proto.InternalMessageInfo

type QueryCallapiResponse struct {
	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryCallapiResponse) Reset()         { *m = QueryCallapiResponse{} }
func (m *QueryCallapiResponse) String() string { return proto.CompactTextString(m) }
func (*QueryCallapiResponse) ProtoMessage()    {}
func (*QueryCallapiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{5}
}
func (m *QueryCallapiResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryCallapiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryCallapiResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryCallapiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryCallapiResponse.Merge(m, src)
}
func (m *QueryCallapiResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryCallapiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryCallapiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryCallapiResponse proto.InternalMessageInfo

func (m *QueryCallapiResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *QueryCallapiResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetgeolocationsRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryGetgeolocationsRequest) Reset()         { *m = QueryGetgeolocationsRequest{} }
func (m *QueryGetgeolocationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetgeolocationsRequest) ProtoMessage()    {}
func (*QueryGetgeolocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{6}
}
func (m *QueryGetgeolocationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetgeolocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetgeolocationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetgeolocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetgeolocationsRequest.Merge(m, src)
}
func (m *QueryGetgeolocationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetgeolocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetgeolocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetgeolocationsRequest proto.InternalMessageInfo

func (m *QueryGetgeolocationsRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type QueryGetgeolocationsResponse struct {
	Geolocations []string `protobuf:"bytes,1,rep,name=geolocations,proto3" json:"geolocations,omitempty"`
}

func (m *QueryGetgeolocationsResponse) Reset()         { *m = QueryGetgeolocationsResponse{} }
func (m *QueryGetgeolocationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetgeolocationsResponse) ProtoMessage()    {}
func (*QueryGetgeolocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_305d87302e6f30c1, []int{7}
}
func (m *QueryGetgeolocationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetgeolocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetgeolocationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetgeolocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetgeolocationsResponse.Merge(m, src)
}
func (m *QueryGetgeolocationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetgeolocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetgeolocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetgeolocationsResponse proto.InternalMessageInfo

func (m *QueryGetgeolocationsResponse) GetGeolocations() []string {
	if m != nil {
		return m.Geolocations
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "testhellochain.testhellochain.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "testhellochain.testhellochain.QueryParamsResponse")
	proto.RegisterType((*QueryShowvenuesRequest)(nil), "testhellochain.testhellochain.QueryShowvenuesRequest")
	proto.RegisterType((*QueryShowvenuesResponse)(nil), "testhellochain.testhellochain.QueryShowvenuesResponse")
	proto.RegisterType((*QueryCallapiRequest)(nil), "testhellochain.testhellochain.QueryCallapiRequest")
	proto.RegisterType((*QueryCallapiResponse)(nil), "testhellochain.testhellochain.QueryCallapiResponse")
	proto.RegisterType((*QueryGetgeolocationsRequest)(nil), "testhellochain.testhellochain.QueryGetgeolocationsRequest")
	proto.RegisterType((*QueryGetgeolocationsResponse)(nil), "testhellochain.testhellochain.QueryGetgeolocationsResponse")
}

func init() { proto.RegisterFile("testhellochain/query.proto", fileDescriptor_305d87302e6f30c1) }

var fileDescriptor_305d87302e6f30c1 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xb3, 0xfd, 0x13, 0xc8, 0x14, 0x09, 0xb4, 0x04, 0xa8, 0xdc, 0x62, 0x2a, 0x8b, 0xb4,
	0x01, 0x84, 0x57, 0x49, 0xa1, 0x87, 0x82, 0x84, 0x94, 0x4a, 0xed, 0xb5, 0x18, 0x89, 0x43, 0x4f,
	0x6c, 0x9c, 0x95, 0x63, 0xc9, 0xf1, 0xba, 0x59, 0xa7, 0x10, 0x21, 0x2e, 0x3c, 0x01, 0x12, 0xf7,
	0x1e, 0x78, 0x00, 0x9e, 0x23, 0xdc, 0x2a, 0x71, 0xe1, 0x84, 0x50, 0xc2, 0x83, 0x20, 0xef, 0x6e,
	0x48, 0xed, 0x44, 0x38, 0xe1, 0xb6, 0x9e, 0xdd, 0x6f, 0xe6, 0x37, 0x5f, 0x3e, 0x05, 0x8c, 0x98,
	0x89, 0xb8, 0xcd, 0x82, 0x80, 0xbb, 0x6d, 0xea, 0x87, 0xe4, 0xb4, 0xc7, 0xba, 0x7d, 0x3b, 0xea,
	0xf2, 0x98, 0xe3, 0xbb, 0xe9, 0x3b, 0x3b, 0xfd, 0x69, 0x64, 0xa5, 0x67, 0x2c, 0xec, 0x31, 0x25,
	0x35, 0xca, 0x1e, 0xf7, 0xb8, 0x3c, 0x92, 0xe4, 0xa4, 0xab, 0x9b, 0x1e, 0xe7, 0x5e, 0xc0, 0x08,
	0x8d, 0x7c, 0x42, 0xc3, 0x90, 0xc7, 0x34, 0xf6, 0x79, 0x28, 0xf4, 0xed, 0x43, 0x97, 0x8b, 0x0e,
	0x17, 0xa4, 0x49, 0x05, 0x53, 0x1c, 0xe4, 0xac, 0xd6, 0x64, 0x31, 0xad, 0x91, 0x88, 0x7a, 0x7e,
	0x28, 0x1f, 0xeb, 0xb7, 0x1b, 0x99, 0xd9, 0x11, 0xed, 0xd2, 0x8e, 0x6e, 0x64, 0x95, 0x01, 0xbf,
	0x4c, 0xe4, 0xc7, 0xb2, 0xe8, 0xb0, 0xd3, 0x1e, 0x13, 0xb1, 0x75, 0x02, 0x37, 0x53, 0x55, 0x11,
	0xf1, 0x50, 0x30, 0x7c, 0x00, 0x45, 0x25, 0x5e, 0x47, 0x5b, 0xa8, 0xba, 0x56, 0xaf, 0xd8, 0xff,
	0xdc, 0xda, 0x56, 0xf2, 0xc6, 0xca, 0xe0, 0xe7, 0xbd, 0x82, 0xa3, 0xa5, 0xd6, 0x1b, 0xb8, 0x2d,
	0x7b, 0xbf, 0x6a, 0xf3, 0xb7, 0xd2, 0x86, 0xf1, 0x54, 0x7c, 0x08, 0x30, 0x81, 0xd7, 0x23, 0xb6,
	0x6d, 0xb5, 0xa9, 0x9d, 0x6c, 0x6a, 0x2b, 0xc7, 0xf5, 0xa6, 0xf6, 0x31, 0xf5, 0x98, 0xd6, 0x3a,
	0x97, 0x94, 0xd6, 0x39, 0x82, 0x3b, 0x53, 0x23, 0xf4, 0x0a, 0xfb, 0xb0, 0xfa, 0x3a, 0xa9, 0xac,
	0xa3, 0xad, 0xe5, 0xea, 0x5a, 0xfd, 0x7e, 0xce, 0x06, 0xf2, 0xad, 0xa3, 0x24, 0xf8, 0x28, 0xc5,
	0xb7, 0x24, 0xf9, 0x76, 0x72, 0xf9, 0xd4, 0xe0, 0x14, 0xe0, 0x2d, 0x6d, 0xef, 0x01, 0x0d, 0x02,
	0x1a, 0xf9, 0x63, 0xd7, 0x0f, 0xa1, 0x9c, 0x2e, 0x6b, 0x66, 0x03, 0xae, 0xba, 0x34, 0x66, 0x1e,
	0xef, 0xf6, 0xa5, 0x2b, 0x25, 0xe7, 0xef, 0x37, 0xc6, 0xb0, 0x12, 0xd2, 0x0e, 0x93, 0x34, 0x25,
	0x47, 0x9e, 0x2d, 0x02, 0x1b, 0xb2, 0xcf, 0x11, 0x8b, 0x3d, 0xc6, 0x03, 0xee, 0xaa, 0xe8, 0x8c,
	0x6d, 0xbe, 0x01, 0xcb, 0x2d, 0xbf, 0xa5, 0x3b, 0x25, 0x47, 0xab, 0x01, 0x9b, 0xb3, 0x05, 0x1a,
	0xc0, 0x82, 0x6b, 0x97, 0xeb, 0xd2, 0xbb, 0x92, 0x93, 0xaa, 0xd5, 0xbf, 0xad, 0xc2, 0xaa, 0x6c,
	0x82, 0xcf, 0x11, 0x14, 0xd5, 0x2f, 0x8f, 0x6b, 0x39, 0xf6, 0x4e, 0x47, 0xcf, 0xa8, 0x2f, 0x22,
	0x51, 0x7c, 0xd6, 0xe3, 0x8f, 0xdf, 0x7f, 0x7f, 0x5e, 0xda, 0xc1, 0x15, 0x92, 0x89, 0xfa, 0xcc,
	0xe4, 0xe3, 0xaf, 0x08, 0x60, 0x12, 0x0d, 0xfc, 0x74, 0x9e, 0x89, 0x53, 0x69, 0x35, 0xf6, 0x16,
	0x95, 0x69, 0xd8, 0x9a, 0x84, 0x7d, 0x84, 0x1f, 0xe4, 0xc0, 0x8a, 0x09, 0xe1, 0x17, 0x04, 0x57,
	0x74, 0x28, 0xf0, 0x5c, 0xfe, 0xa4, 0x83, 0x65, 0xec, 0x2e, 0xa4, 0xd1, 0x9c, 0xb6, 0xe4, 0xac,
	0xe2, 0xed, 0x1c, 0x4e, 0x57, 0x83, 0x0d, 0x10, 0x5c, 0xcf, 0x04, 0x08, 0xef, 0xcf, 0x33, 0x78,
	0x76, 0x4c, 0x8d, 0x67, 0xff, 0xa5, 0xd5, 0xf0, 0xcf, 0x25, 0xfc, 0x1e, 0x7e, 0x92, 0x03, 0xef,
	0xa5, 0xf5, 0xe4, 0x7d, 0xcb, 0x6f, 0x7d, 0x68, 0xbc, 0x18, 0x0c, 0x4d, 0x74, 0x31, 0x34, 0xd1,
	0xaf, 0xa1, 0x89, 0x3e, 0x8d, 0xcc, 0xc2, 0xc5, 0xc8, 0x2c, 0xfc, 0x18, 0x99, 0x85, 0x93, 0x4a,
	0x46, 0xff, 0x6e, 0xaa, 0x7f, 0x3f, 0x62, 0xa2, 0x59, 0x94, 0x7f, 0xae, 0xbb, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x4c, 0x8e, 0x67, 0x9b, 0x32, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Showvenues items.
	Showvenues(ctx context.Context, in *QueryShowvenuesRequest, opts ...grpc.CallOption) (*QueryShowvenuesResponse, error)
	// Queries a list of Callapi items.
	Callapi(ctx context.Context, in *QueryCallapiRequest, opts ...grpc.CallOption) (*QueryCallapiResponse, error)
	// Queries a list of Getgeolocations items.
	Getgeolocations(ctx context.Context, in *QueryGetgeolocationsRequest, opts ...grpc.CallOption) (*QueryGetgeolocationsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.testhellochain.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Showvenues(ctx context.Context, in *QueryShowvenuesRequest, opts ...grpc.CallOption) (*QueryShowvenuesResponse, error) {
	out := new(QueryShowvenuesResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.testhellochain.Query/Showvenues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Callapi(ctx context.Context, in *QueryCallapiRequest, opts ...grpc.CallOption) (*QueryCallapiResponse, error) {
	out := new(QueryCallapiResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.testhellochain.Query/Callapi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Getgeolocations(ctx context.Context, in *QueryGetgeolocationsRequest, opts ...grpc.CallOption) (*QueryGetgeolocationsResponse, error) {
	out := new(QueryGetgeolocationsResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.testhellochain.Query/Getgeolocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Showvenues items.
	Showvenues(context.Context, *QueryShowvenuesRequest) (*QueryShowvenuesResponse, error)
	// Queries a list of Callapi items.
	Callapi(context.Context, *QueryCallapiRequest) (*QueryCallapiResponse, error)
	// Queries a list of Getgeolocations items.
	Getgeolocations(context.Context, *QueryGetgeolocationsRequest) (*QueryGetgeolocationsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Showvenues(ctx context.Context, req *QueryShowvenuesRequest) (*QueryShowvenuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Showvenues not implemented")
}
func (*UnimplementedQueryServer) Callapi(ctx context.Context, req *QueryCallapiRequest) (*QueryCallapiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Callapi not implemented")
}
func (*UnimplementedQueryServer) Getgeolocations(ctx context.Context, req *QueryGetgeolocationsRequest) (*QueryGetgeolocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Getgeolocations not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.testhellochain.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Showvenues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryShowvenuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Showvenues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.testhellochain.Query/Showvenues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Showvenues(ctx, req.(*QueryShowvenuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Callapi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCallapiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Callapi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.testhellochain.Query/Callapi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Callapi(ctx, req.(*QueryCallapiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Getgeolocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetgeolocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Getgeolocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.testhellochain.Query/Getgeolocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Getgeolocations(ctx, req.(*QueryGetgeolocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testhellochain.testhellochain.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Showvenues",
			Handler:    _Query_Showvenues_Handler,
		},
		{
			MethodName: "Callapi",
			Handler:    _Query_Callapi_Handler,
		},
		{
			MethodName: "Getgeolocations",
			Handler:    _Query_Getgeolocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testhellochain/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryShowvenuesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowvenuesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowvenuesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryShowvenuesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryShowvenuesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryShowvenuesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Venue) > 0 {
		for iNdEx := len(m.Venue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Venue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryCallapiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCallapiRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCallapiRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryCallapiResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryCallapiResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryCallapiResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Category) > 0 {
		i -= len(m.Category)
		copy(dAtA[i:], m.Category)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Category)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetgeolocationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetgeolocationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetgeolocationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetgeolocationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetgeolocationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetgeolocationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Geolocations) > 0 {
		for iNdEx := len(m.Geolocations) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Geolocations[iNdEx])
			copy(dAtA[i:], m.Geolocations[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Geolocations[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryShowvenuesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryShowvenuesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Venue) > 0 {
		for _, e := range m.Venue {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryCallapiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryCallapiResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Category)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetgeolocationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetgeolocationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Geolocations) > 0 {
		for _, s := range m.Geolocations {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowvenuesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowvenuesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowvenuesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryShowvenuesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryShowvenuesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryShowvenuesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Venue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Venue = append(m.Venue, &Venue{})
			if err := m.Venue[len(m.Venue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCallapiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCallapiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCallapiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryCallapiResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryCallapiResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryCallapiResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetgeolocationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetgeolocationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetgeolocationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetgeolocationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetgeolocationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetgeolocationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Geolocations", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Geolocations = append(m.Geolocations, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
