// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: estimator/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetApiHitsRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetApiHitsRequest) Reset()         { *m = QueryGetApiHitsRequest{} }
func (m *QueryGetApiHitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiHitsRequest) ProtoMessage()    {}
func (*QueryGetApiHitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{2}
}
func (m *QueryGetApiHitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiHitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiHitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiHitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiHitsRequest.Merge(m, src)
}
func (m *QueryGetApiHitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiHitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiHitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiHitsRequest proto.InternalMessageInfo

func (m *QueryGetApiHitsRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetApiHitsResponse struct {
	ApiHits ApiHits `protobuf:"bytes,1,opt,name=ApiHits,proto3" json:"ApiHits"`
}

func (m *QueryGetApiHitsResponse) Reset()         { *m = QueryGetApiHitsResponse{} }
func (m *QueryGetApiHitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiHitsResponse) ProtoMessage()    {}
func (*QueryGetApiHitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{3}
}
func (m *QueryGetApiHitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiHitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiHitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiHitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiHitsResponse.Merge(m, src)
}
func (m *QueryGetApiHitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiHitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiHitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiHitsResponse proto.InternalMessageInfo

func (m *QueryGetApiHitsResponse) GetApiHits() ApiHits {
	if m != nil {
		return m.ApiHits
	}
	return ApiHits{}
}

type QueryAllApiHitsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiHitsRequest) Reset()         { *m = QueryAllApiHitsRequest{} }
func (m *QueryAllApiHitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiHitsRequest) ProtoMessage()    {}
func (*QueryAllApiHitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{4}
}
func (m *QueryAllApiHitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiHitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiHitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiHitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiHitsRequest.Merge(m, src)
}
func (m *QueryAllApiHitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiHitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiHitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiHitsRequest proto.InternalMessageInfo

func (m *QueryAllApiHitsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllApiHitsResponse struct {
	ApiHits    []ApiHits           `protobuf:"bytes,1,rep,name=ApiHits,proto3" json:"ApiHits"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiHitsResponse) Reset()         { *m = QueryAllApiHitsResponse{} }
func (m *QueryAllApiHitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiHitsResponse) ProtoMessage()    {}
func (*QueryAllApiHitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{5}
}
func (m *QueryAllApiHitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiHitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiHitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiHitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiHitsResponse.Merge(m, src)
}
func (m *QueryAllApiHitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiHitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiHitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiHitsResponse proto.InternalMessageInfo

func (m *QueryAllApiHitsResponse) GetApiHits() []ApiHits {
	if m != nil {
		return m.ApiHits
	}
	return nil
}

func (m *QueryAllApiHitsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetApiDataRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetApiDataRequest) Reset()         { *m = QueryGetApiDataRequest{} }
func (m *QueryGetApiDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiDataRequest) ProtoMessage()    {}
func (*QueryGetApiDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{6}
}
func (m *QueryGetApiDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiDataRequest.Merge(m, src)
}
func (m *QueryGetApiDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiDataRequest proto.InternalMessageInfo

func (m *QueryGetApiDataRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetApiDataResponse struct {
	ApiData ApiData `protobuf:"bytes,1,opt,name=ApiData,proto3" json:"ApiData"`
}

func (m *QueryGetApiDataResponse) Reset()         { *m = QueryGetApiDataResponse{} }
func (m *QueryGetApiDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiDataResponse) ProtoMessage()    {}
func (*QueryGetApiDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{7}
}
func (m *QueryGetApiDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiDataResponse.Merge(m, src)
}
func (m *QueryGetApiDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiDataResponse proto.InternalMessageInfo

func (m *QueryGetApiDataResponse) GetApiData() ApiData {
	if m != nil {
		return m.ApiData
	}
	return ApiData{}
}

type QueryAllApiDataRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiDataRequest) Reset()         { *m = QueryAllApiDataRequest{} }
func (m *QueryAllApiDataRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiDataRequest) ProtoMessage()    {}
func (*QueryAllApiDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{8}
}
func (m *QueryAllApiDataRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiDataRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiDataRequest.Merge(m, src)
}
func (m *QueryAllApiDataRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiDataRequest proto.InternalMessageInfo

func (m *QueryAllApiDataRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllApiDataResponse struct {
	ApiData    []ApiData           `protobuf:"bytes,1,rep,name=ApiData,proto3" json:"ApiData"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiDataResponse) Reset()         { *m = QueryAllApiDataResponse{} }
func (m *QueryAllApiDataResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiDataResponse) ProtoMessage()    {}
func (*QueryAllApiDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{9}
}
func (m *QueryAllApiDataResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiDataResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiDataResponse.Merge(m, src)
}
func (m *QueryAllApiDataResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiDataResponse proto.InternalMessageInfo

func (m *QueryAllApiDataResponse) GetApiData() []ApiData {
	if m != nil {
		return m.ApiData
	}
	return nil
}

func (m *QueryAllApiDataResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetApiCountMapRequest struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *QueryGetApiCountMapRequest) Reset()         { *m = QueryGetApiCountMapRequest{} }
func (m *QueryGetApiCountMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiCountMapRequest) ProtoMessage()    {}
func (*QueryGetApiCountMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{10}
}
func (m *QueryGetApiCountMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiCountMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiCountMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiCountMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiCountMapRequest.Merge(m, src)
}
func (m *QueryGetApiCountMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiCountMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiCountMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiCountMapRequest proto.InternalMessageInfo

func (m *QueryGetApiCountMapRequest) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type QueryGetApiCountMapResponse struct {
	ApiCountMap ApiCountMap `protobuf:"bytes,1,opt,name=apiCountMap,proto3" json:"apiCountMap"`
}

func (m *QueryGetApiCountMapResponse) Reset()         { *m = QueryGetApiCountMapResponse{} }
func (m *QueryGetApiCountMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetApiCountMapResponse) ProtoMessage()    {}
func (*QueryGetApiCountMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{11}
}
func (m *QueryGetApiCountMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetApiCountMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetApiCountMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetApiCountMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetApiCountMapResponse.Merge(m, src)
}
func (m *QueryGetApiCountMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetApiCountMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetApiCountMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetApiCountMapResponse proto.InternalMessageInfo

func (m *QueryGetApiCountMapResponse) GetApiCountMap() ApiCountMap {
	if m != nil {
		return m.ApiCountMap
	}
	return ApiCountMap{}
}

type QueryAllApiCountMapRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiCountMapRequest) Reset()         { *m = QueryAllApiCountMapRequest{} }
func (m *QueryAllApiCountMapRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiCountMapRequest) ProtoMessage()    {}
func (*QueryAllApiCountMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{12}
}
func (m *QueryAllApiCountMapRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiCountMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiCountMapRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiCountMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiCountMapRequest.Merge(m, src)
}
func (m *QueryAllApiCountMapRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiCountMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiCountMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiCountMapRequest proto.InternalMessageInfo

func (m *QueryAllApiCountMapRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllApiCountMapResponse struct {
	ApiCountMap []ApiCountMap       `protobuf:"bytes,1,rep,name=apiCountMap,proto3" json:"apiCountMap"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllApiCountMapResponse) Reset()         { *m = QueryAllApiCountMapResponse{} }
func (m *QueryAllApiCountMapResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllApiCountMapResponse) ProtoMessage()    {}
func (*QueryAllApiCountMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1ebbed30e96b0faa, []int{13}
}
func (m *QueryAllApiCountMapResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllApiCountMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllApiCountMapResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllApiCountMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllApiCountMapResponse.Merge(m, src)
}
func (m *QueryAllApiCountMapResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllApiCountMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllApiCountMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllApiCountMapResponse proto.InternalMessageInfo

func (m *QueryAllApiCountMapResponse) GetApiCountMap() []ApiCountMap {
	if m != nil {
		return m.ApiCountMap
	}
	return nil
}

func (m *QueryAllApiCountMapResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "testhellochain.estimator.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "testhellochain.estimator.QueryParamsResponse")
	proto.RegisterType((*QueryGetApiHitsRequest)(nil), "testhellochain.estimator.QueryGetApiHitsRequest")
	proto.RegisterType((*QueryGetApiHitsResponse)(nil), "testhellochain.estimator.QueryGetApiHitsResponse")
	proto.RegisterType((*QueryAllApiHitsRequest)(nil), "testhellochain.estimator.QueryAllApiHitsRequest")
	proto.RegisterType((*QueryAllApiHitsResponse)(nil), "testhellochain.estimator.QueryAllApiHitsResponse")
	proto.RegisterType((*QueryGetApiDataRequest)(nil), "testhellochain.estimator.QueryGetApiDataRequest")
	proto.RegisterType((*QueryGetApiDataResponse)(nil), "testhellochain.estimator.QueryGetApiDataResponse")
	proto.RegisterType((*QueryAllApiDataRequest)(nil), "testhellochain.estimator.QueryAllApiDataRequest")
	proto.RegisterType((*QueryAllApiDataResponse)(nil), "testhellochain.estimator.QueryAllApiDataResponse")
	proto.RegisterType((*QueryGetApiCountMapRequest)(nil), "testhellochain.estimator.QueryGetApiCountMapRequest")
	proto.RegisterType((*QueryGetApiCountMapResponse)(nil), "testhellochain.estimator.QueryGetApiCountMapResponse")
	proto.RegisterType((*QueryAllApiCountMapRequest)(nil), "testhellochain.estimator.QueryAllApiCountMapRequest")
	proto.RegisterType((*QueryAllApiCountMapResponse)(nil), "testhellochain.estimator.QueryAllApiCountMapResponse")
}

func init() { proto.RegisterFile("estimator/query.proto", fileDescriptor_1ebbed30e96b0faa) }

var fileDescriptor_1ebbed30e96b0faa = []byte{
	// 719 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0xcd, 0x4f, 0x13, 0x4f,
	0x18, 0xc7, 0x3b, 0x85, 0x1f, 0x84, 0x21, 0xe1, 0x30, 0x3f, 0xc4, 0xa6, 0x6a, 0xad, 0x13, 0x15,
	0x24, 0xba, 0x63, 0x01, 0x4d, 0xf4, 0x60, 0x52, 0x34, 0xe2, 0x85, 0x04, 0x9b, 0x78, 0x31, 0x26,
	0x38, 0xb4, 0x93, 0x32, 0xc9, 0x76, 0x67, 0xe9, 0x0e, 0x46, 0x42, 0xb8, 0x78, 0xf0, 0xaa, 0x89,
	0x67, 0xe3, 0xc9, 0xab, 0x37, 0xfe, 0x07, 0x8e, 0x24, 0x5e, 0x3c, 0x19, 0x03, 0xfe, 0x21, 0x66,
	0x5e, 0xb6, 0xdd, 0x17, 0x96, 0x6e, 0x11, 0x6f, 0xed, 0xcc, 0xf3, 0xf2, 0xf9, 0x7e, 0x9f, 0xee,
	0xb3, 0x85, 0x17, 0x58, 0x20, 0x79, 0x87, 0x4a, 0xd1, 0x25, 0x5b, 0xdb, 0xac, 0xbb, 0xe3, 0xf8,
	0x5d, 0x21, 0x05, 0x2a, 0x49, 0x16, 0xc8, 0x4d, 0xe6, 0xba, 0xa2, 0xb9, 0x49, 0xb9, 0xe7, 0xf4,
	0xa2, 0xca, 0xd3, 0x6d, 0xd1, 0x16, 0x3a, 0x88, 0xa8, 0x4f, 0x26, 0xbe, 0x7c, 0xb9, 0x2d, 0x44,
	0xdb, 0x65, 0x84, 0xfa, 0x9c, 0x50, 0xcf, 0x13, 0x92, 0x4a, 0x2e, 0xbc, 0xc0, 0xde, 0xce, 0x37,
	0x45, 0xd0, 0x11, 0x01, 0xd9, 0xa0, 0x01, 0x33, 0x6d, 0xc8, 0x9b, 0xda, 0x06, 0x93, 0xb4, 0x46,
	0x7c, 0xda, 0xe6, 0x9e, 0x0e, 0xb6, 0xb1, 0x33, 0x7d, 0x20, 0x9f, 0x76, 0x69, 0x27, 0xac, 0x51,
	0xea, 0x9f, 0x53, 0x9f, 0xaf, 0x6f, 0x72, 0x99, 0x71, 0xd3, 0xa2, 0x92, 0xda, 0x9b, 0x2b, 0xf1,
	0x9b, 0xa6, 0xd8, 0xf6, 0xe4, 0x7a, 0x87, 0xfa, 0xe6, 0x1a, 0x4f, 0x43, 0xf4, 0x5c, 0xc1, 0xac,
	0xe9, 0x3e, 0x0d, 0xb6, 0xb5, 0xcd, 0x02, 0x89, 0x5f, 0xc0, 0xff, 0x63, 0xa7, 0x81, 0x2f, 0xbc,
	0x80, 0xa1, 0x47, 0x70, 0xcc, 0xf0, 0x94, 0x40, 0x15, 0xcc, 0x4d, 0x2e, 0x54, 0x9d, 0x2c, 0x8b,
	0x1c, 0x93, 0xb9, 0x3c, 0x7a, 0xf0, 0xf3, 0x6a, 0xa1, 0x61, 0xb3, 0xf0, 0x1c, 0x9c, 0xd1, 0x65,
	0x57, 0x98, 0xac, 0xfb, 0xfc, 0x19, 0x97, 0x61, 0x43, 0x34, 0x05, 0x8b, 0xbc, 0xa5, 0xab, 0x8e,
	0x36, 0x8a, 0xbc, 0x85, 0x5f, 0xc1, 0x8b, 0xa9, 0x48, 0x0b, 0x51, 0x87, 0xe3, 0xf6, 0xc8, 0x52,
	0x5c, 0xcb, 0xa6, 0xb0, 0x81, 0x16, 0x23, 0xcc, 0xc3, 0xaf, 0x2d, 0x47, 0xdd, 0x75, 0x13, 0x1c,
	0x4f, 0x21, 0xec, 0x4f, 0xc3, 0xd6, 0xbf, 0xe9, 0x98, 0xd1, 0x39, 0x6a, 0x74, 0x8e, 0xf9, 0x85,
	0xd8, 0xd1, 0x39, 0x6b, 0xb4, 0xcd, 0x6c, 0x6e, 0x23, 0x92, 0x89, 0xbf, 0x02, 0x2b, 0x20, 0xda,
	0xe2, 0x24, 0x01, 0x23, 0x67, 0x11, 0x80, 0x56, 0x62, 0x98, 0x45, 0x8d, 0x39, 0x3b, 0x10, 0xd3,
	0xf4, 0x8f, 0x71, 0xc6, 0x27, 0xf2, 0x84, 0x4a, 0x9a, 0x6f, 0x22, 0x26, 0x32, 0x26, 0x48, 0x1d,
	0xe5, 0x9a, 0x88, 0x0a, 0x8c, 0x08, 0x52, 0x5f, 0x13, 0x13, 0x89, 0x72, 0xfc, 0xa3, 0x89, 0x64,
	0x0b, 0x18, 0x39, 0x8b, 0x80, 0xf3, 0x9b, 0xc8, 0x7d, 0x58, 0x8e, 0xf8, 0xfc, 0x58, 0x3d, 0xae,
	0xab, 0xd4, 0x0f, 0xdd, 0x28, 0xc1, 0xf1, 0x66, 0x97, 0x29, 0x10, 0x6d, 0xc5, 0x44, 0x23, 0xfc,
	0x8a, 0x5d, 0x78, 0xe9, 0xc4, 0x3c, 0x2b, 0x71, 0x15, 0x4e, 0xd2, 0xfe, 0xb1, 0xf5, 0xf1, 0xc6,
	0xa9, 0x32, 0xc3, 0x60, 0x2b, 0x35, 0x9a, 0x8f, 0x5b, 0x96, 0xd2, 0x98, 0x99, 0xa4, 0x3c, 0xaf,
	0x99, 0xed, 0x03, 0x2b, 0x2a, 0xd9, 0x26, 0x4b, 0xd4, 0xc8, 0xdf, 0x88, 0x3a, 0xb7, 0x19, 0x2e,
	0xbc, 0x9f, 0x80, 0xff, 0x69, 0x6e, 0xf4, 0x01, 0xc0, 0x31, 0xb3, 0x0a, 0xd1, 0xed, 0x6c, 0xae,
	0xf4, 0x06, 0x2e, 0xdf, 0xc9, 0x19, 0x6d, 0xba, 0xe3, 0xb9, 0x77, 0xdf, 0x7f, 0x7f, 0x2a, 0x62,
	0x54, 0x25, 0xf1, 0x34, 0x92, 0x7c, 0x93, 0xa0, 0x2f, 0xa0, 0xb7, 0x7e, 0xd0, 0xdd, 0x01, 0x4d,
	0x52, 0x7b, 0xba, 0x5c, 0x1b, 0x22, 0xc3, 0xa2, 0x11, 0x8d, 0x76, 0x0b, 0xcd, 0x66, 0xa3, 0x85,
	0x2f, 0x33, 0xb2, 0xcb, 0x5b, 0x7b, 0xe8, 0x33, 0x80, 0xd0, 0x16, 0xa9, 0xbb, 0xee, 0x40, 0xc8,
	0xd4, 0x12, 0x1f, 0x08, 0x99, 0xde, 0xc9, 0x78, 0x5e, 0x43, 0x5e, 0x47, 0x78, 0x30, 0x64, 0xe8,
	0xa0, 0x7e, 0xec, 0xf3, 0x39, 0x18, 0xd9, 0x67, 0x39, 0x1d, 0x8c, 0xae, 0xa7, 0xbc, 0x0e, 0xaa,
	0x97, 0x7e, 0xcc, 0x41, 0x55, 0x24, 0xbf, 0x83, 0xc3, 0x40, 0xa6, 0x77, 0x68, 0x5e, 0x07, 0x15,
	0x24, 0xda, 0x07, 0x70, 0x32, 0xf2, 0x2c, 0xa2, 0xa5, 0x5c, 0x9e, 0x24, 0xb6, 0x4c, 0xf9, 0xde,
	0x90, 0x59, 0x16, 0xf4, 0x81, 0x06, 0x5d, 0x44, 0xb5, 0xd3, 0x41, 0x7b, 0x7f, 0x94, 0xc8, 0xae,
	0x5d, 0xb1, 0x7b, 0xe8, 0x1b, 0x80, 0x53, 0x91, 0x92, 0xca, 0xdb, 0xa5, 0x5c, 0x4e, 0x0d, 0x8b,
	0x7e, 0xf2, 0xbe, 0xcb, 0xfb, 0x43, 0xe8, 0xa1, 0x2f, 0x3f, 0x3c, 0x38, 0xaa, 0x80, 0xc3, 0xa3,
	0x0a, 0xf8, 0x75, 0x54, 0x01, 0x1f, 0x8f, 0x2b, 0x85, 0xc3, 0xe3, 0x4a, 0xe1, 0xc7, 0x71, 0xa5,
	0xf0, 0xb2, 0x9a, 0xa8, 0xf0, 0x36, 0x52, 0x43, 0xee, 0xf8, 0x2c, 0xd8, 0x18, 0xd3, 0x7f, 0x10,
	0x17, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x63, 0xd5, 0x99, 0x1e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a ApiHits by id.
	ApiHits(ctx context.Context, in *QueryGetApiHitsRequest, opts ...grpc.CallOption) (*QueryGetApiHitsResponse, error)
	// Queries a list of ApiHits items.
	ApiHitsAll(ctx context.Context, in *QueryAllApiHitsRequest, opts ...grpc.CallOption) (*QueryAllApiHitsResponse, error)
	// Queries a ApiData by id.
	ApiData(ctx context.Context, in *QueryGetApiDataRequest, opts ...grpc.CallOption) (*QueryGetApiDataResponse, error)
	// Queries a list of ApiData items.
	ApiDataAll(ctx context.Context, in *QueryAllApiDataRequest, opts ...grpc.CallOption) (*QueryAllApiDataResponse, error)
	// Queries a ApiCountMap by index.
	ApiCountMap(ctx context.Context, in *QueryGetApiCountMapRequest, opts ...grpc.CallOption) (*QueryGetApiCountMapResponse, error)
	// Queries a list of ApiCountMap items.
	ApiCountMapAll(ctx context.Context, in *QueryAllApiCountMapRequest, opts ...grpc.CallOption) (*QueryAllApiCountMapResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiHits(ctx context.Context, in *QueryGetApiHitsRequest, opts ...grpc.CallOption) (*QueryGetApiHitsResponse, error) {
	out := new(QueryGetApiHitsResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiHits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiHitsAll(ctx context.Context, in *QueryAllApiHitsRequest, opts ...grpc.CallOption) (*QueryAllApiHitsResponse, error) {
	out := new(QueryAllApiHitsResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiHitsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiData(ctx context.Context, in *QueryGetApiDataRequest, opts ...grpc.CallOption) (*QueryGetApiDataResponse, error) {
	out := new(QueryGetApiDataResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiDataAll(ctx context.Context, in *QueryAllApiDataRequest, opts ...grpc.CallOption) (*QueryAllApiDataResponse, error) {
	out := new(QueryAllApiDataResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiDataAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiCountMap(ctx context.Context, in *QueryGetApiCountMapRequest, opts ...grpc.CallOption) (*QueryGetApiCountMapResponse, error) {
	out := new(QueryGetApiCountMapResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiCountMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ApiCountMapAll(ctx context.Context, in *QueryAllApiCountMapRequest, opts ...grpc.CallOption) (*QueryAllApiCountMapResponse, error) {
	out := new(QueryAllApiCountMapResponse)
	err := c.cc.Invoke(ctx, "/testhellochain.estimator.Query/ApiCountMapAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a ApiHits by id.
	ApiHits(context.Context, *QueryGetApiHitsRequest) (*QueryGetApiHitsResponse, error)
	// Queries a list of ApiHits items.
	ApiHitsAll(context.Context, *QueryAllApiHitsRequest) (*QueryAllApiHitsResponse, error)
	// Queries a ApiData by id.
	ApiData(context.Context, *QueryGetApiDataRequest) (*QueryGetApiDataResponse, error)
	// Queries a list of ApiData items.
	ApiDataAll(context.Context, *QueryAllApiDataRequest) (*QueryAllApiDataResponse, error)
	// Queries a ApiCountMap by index.
	ApiCountMap(context.Context, *QueryGetApiCountMapRequest) (*QueryGetApiCountMapResponse, error)
	// Queries a list of ApiCountMap items.
	ApiCountMapAll(context.Context, *QueryAllApiCountMapRequest) (*QueryAllApiCountMapResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ApiHits(ctx context.Context, req *QueryGetApiHitsRequest) (*QueryGetApiHitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiHits not implemented")
}
func (*UnimplementedQueryServer) ApiHitsAll(ctx context.Context, req *QueryAllApiHitsRequest) (*QueryAllApiHitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiHitsAll not implemented")
}
func (*UnimplementedQueryServer) ApiData(ctx context.Context, req *QueryGetApiDataRequest) (*QueryGetApiDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiData not implemented")
}
func (*UnimplementedQueryServer) ApiDataAll(ctx context.Context, req *QueryAllApiDataRequest) (*QueryAllApiDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiDataAll not implemented")
}
func (*UnimplementedQueryServer) ApiCountMap(ctx context.Context, req *QueryGetApiCountMapRequest) (*QueryGetApiCountMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiCountMap not implemented")
}
func (*UnimplementedQueryServer) ApiCountMapAll(ctx context.Context, req *QueryAllApiCountMapRequest) (*QueryAllApiCountMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApiCountMapAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiHits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetApiHitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiHits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiHits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiHits(ctx, req.(*QueryGetApiHitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiHitsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllApiHitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiHitsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiHitsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiHitsAll(ctx, req.(*QueryAllApiHitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetApiDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiData(ctx, req.(*QueryGetApiDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiDataAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllApiDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiDataAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiDataAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiDataAll(ctx, req.(*QueryAllApiDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiCountMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetApiCountMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiCountMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiCountMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiCountMap(ctx, req.(*QueryGetApiCountMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ApiCountMapAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllApiCountMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ApiCountMapAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/testhellochain.estimator.Query/ApiCountMapAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ApiCountMapAll(ctx, req.(*QueryAllApiCountMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "testhellochain.estimator.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ApiHits",
			Handler:    _Query_ApiHits_Handler,
		},
		{
			MethodName: "ApiHitsAll",
			Handler:    _Query_ApiHitsAll_Handler,
		},
		{
			MethodName: "ApiData",
			Handler:    _Query_ApiData_Handler,
		},
		{
			MethodName: "ApiDataAll",
			Handler:    _Query_ApiDataAll_Handler,
		},
		{
			MethodName: "ApiCountMap",
			Handler:    _Query_ApiCountMap_Handler,
		},
		{
			MethodName: "ApiCountMapAll",
			Handler:    _Query_ApiCountMapAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "estimator/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetApiHitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiHitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiHitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApiHitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiHitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiHitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ApiHits.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllApiHitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiHitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiHitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllApiHitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiHitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiHitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ApiHits) > 0 {
		for iNdEx := len(m.ApiHits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApiHits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApiDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApiDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ApiData.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllApiDataRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiDataRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiDataRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllApiDataResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiDataResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiDataResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ApiData) > 0 {
		for iNdEx := len(m.ApiData) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApiData[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApiCountMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiCountMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiCountMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetApiCountMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetApiCountMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetApiCountMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ApiCountMap.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllApiCountMapRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiCountMapRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiCountMapRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllApiCountMapResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllApiCountMapResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllApiCountMapResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ApiCountMap) > 0 {
		for iNdEx := len(m.ApiCountMap) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApiCountMap[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetApiHitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetApiHitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ApiHits.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllApiHitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllApiHitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ApiHits) > 0 {
		for _, e := range m.ApiHits {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetApiDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetApiDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ApiData.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllApiDataRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllApiDataResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ApiData) > 0 {
		for _, e := range m.ApiData {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetApiCountMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetApiCountMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ApiCountMap.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllApiCountMapRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllApiCountMapResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ApiCountMap) > 0 {
		for _, e := range m.ApiCountMap {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiHitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiHitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiHitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiHitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiHitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiHitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiHits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ApiHits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiHitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiHitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiHitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiHitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiHitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiHitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiHits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiHits = append(m.ApiHits, ApiHits{})
			if err := m.ApiHits[len(m.ApiHits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ApiData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiDataRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiDataRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiDataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiDataResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiDataResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiDataResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiData = append(m.ApiData, ApiData{})
			if err := m.ApiData[len(m.ApiData)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiCountMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiCountMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiCountMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetApiCountMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetApiCountMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetApiCountMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiCountMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ApiCountMap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiCountMapRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiCountMapRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiCountMapRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllApiCountMapResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllApiCountMapResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllApiCountMapResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiCountMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiCountMap = append(m.ApiCountMap, ApiCountMap{})
			if err := m.ApiCountMap[len(m.ApiCountMap)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
